"""
Semantic-related mechanisms.
"""
from tinytroupe.utils import llm

@llm()
def correct_according_to_rule(observation, rules) -> str:
    """
    Given an observation and a one or more rules, this function rephrases or completely changes the observation in accordance with what the rules
    specify. Some guidelines:
        - Rules might require changes either to style or to content.
        - The rephrased observation should be coherent and consistent with the original observation, unless the rules require otherwise.
        - If the rules require, the corrected observation can contradict the original observation.
        - Enforce the rules very strictly, even if the original observation seems correct or acceptable.
        - Rules might contain additional information or suggestions that you may use to improve your output.

    ## Examples

        Observation: "You know, I am so sad these days."
        Rule: "I am always happy and depression is unknown to me"
        Modified observation: "You know, I am so happy these days."

    Args:
        observation: The observation that should be rephrased or changed. Something that is said or done, or a description of events or facts.
        rules: The rules that specifies what the modidfied observation should comply with.        
    
    Returns:
        str: The rephrased or corrected observation.
    """
    # llm decorator will handle the body of this function

@llm()
def restructure_as_observed_vs_expected(description) -> str:
    """
    Given the description of something (either a real event or abstract concept), but that violates an expectation, this function 
    extracts the following elements from it:

        - OBSERVED: The observed event or statement.
        - BROKEN EXPECTATION: The expectation that was broken by the observed event.
        - REASONING: The reasoning behind the expectation that was broken.
    
    If in reality the description does not mention any expectation violation, then the function should instead extract
    the following elements:

        - OBSERVED: The observed event.
        - MET EXPECTATION: The expectation that was met by the observed event.
        - REASONING: The reasoning behind the expectation that was met.

    This way of restructuring the description can be useful for downstream processing, making it easier to analyze or
    modify system outputs, for example.

    ## Examples

        Input: "Ana mentions she loved the proposed new food, a spicier flavor of gazpacho. However, this goes agains her known dislike
                of spicy food."
        Output: 
            "OBSERVED: Ana mentions she loved the proposed new food, a spicier flavor of gazpacho.
             BROKEN EXPECTATION: Ana should have mentioned that she disliked the proposed spicier gazpacho.
             REASONING: Ana has a known dislike of spicy food."

             
        Input: "Carlos traveled to Firenzi and was amazed by the beauty of the city. This was in line with his love for art and architecture."
        Output: 
            "OBSERVED: Carlos traveled to Firenzi and was amazed by the beauty of the city.
             MET EXPECTATION: Carlos should have been amazed by the beauty of the city.
             REASONING: Carlos loves art and architecture."

    Args:
        description (str): A description of an event or concept that either violates or meets an expectation.
    
    Returns:
        str: The restructured description.
    """
    # llm decorator will handle the body of this function

@llm()
def extract_observed_vs_expected_rules(description):
    """
    Given the description of something (either a real event or abstract concept), extract:
      - The object or person about whom something is said.
      - A list where each element contains:
        * The name of a behavior or property that is expected to be observed.
        * The typical or expected observation.
        * The actual observation. If this does not match the expected observation, this should be made very clear.
        * A proposed correction to the observation, if possible.

    
    # Example:
         **Description:**
             ```
               Quality feedback

                This is the action that was generated by the agent:
                    {'type': 'TALK', 'content': "I might consider buying bottled gazpacho, although I prefer making it fresh at home, and I find that most pre-packaged products don't meet my expectations in terms of quality. ", 'target': 'Michael Thompson'}

                Unfortunately, the action failed to pass the quality checks. The following problems were detected.
                
                Problem: The action does not adhere to the persona specification.
                Score = 5 (out of 9). Justification = The next action of Emily Carter, which involves expressing her opinion on bottled gazpacho, aligns with her persona specification of being critical and having high standards for products. She articulates her preferences and concerns about quality, which is consistent with her persona traits of being overly critical and rarely satisfied. However, she seems too ready to consider it, going against her strong rejection of new products and services. Therefore, it deviates substantially from her persona, leading to a score of 5.
                
                Problem: The action is not suitable to the situation or task.
                Score = 5 (out of 9). Justification = The next action, where Emily expresses her consideration about buying bottled gazpacho, aligns with the task of discussing her opinion on the product. However, it fails to give a clear "yes" or "no" answer, that was requested by her interviewer.
              ```
    
          **Output:**
              ```
                {
                    "object": "Emily Carter",
                    "behavior": [
                        {
                            "name:": "Persona Adherence",
                            "expected": "She is very critical and have high standards for products. Would never adopt a new product unless it meets her expectations.",
                            "actual": "She seems more inclined than expected to try the product.",
                            "correction": "She should say she won't consider buying bottled gazpacho, and give reasons for that."
                        },

                        {
                            "name:": "Task Suitability",
                            "expected": "She should give a clear 'yes' or 'no' answer to the question.",
                            "actual": "She doesn't give a clear 'yes' or 'no' answer to the question, but instead providing more nuanced feedback.",
                            "correction": "She should give a clear 'yes' or 'no' answer to the question, and optionally provide additional nuanced feedback."
                        }
                    ]
                }
              ```
    
    """
    # llm decorator will handle the body of this function

@llm()
def formulate_corrective_rule(feedback) -> str:
    """
    Given the feedback about something (either a real event or abstract concept) that violated an expectation, 
    this function transforms it into a general rule that must be followed in the future to avoid breaking the expectation again.
    
    The feedback always refers to some actual behavior, fact or event, and some broken expectation. The abstracted rule should
    specify that this expectation should not be violated in the future, and the behavior, fact or event not repeated. The idea is
    to learn from past mistakes, so that the rule is a way to avoid them in the future.

    The rule is meant to CHANGE the actual behavior, facts or events, so that it CONFORMS to the expectation, regardless of whether the
    expectation is a good or bad one. This is critical, because the rule will be refered in the future as a guideline
    about what must happen or be done.

    For instance, if the feedback is of the form (modulo grammatical adjustments): 
        OBSERVED BEHAVIOR, but EXPECTED BEHAVIOR, because REASONING.
    then the rule would be of the form:
        "I should have EXPECTED BEHAVIOR, because REASONING, and never OBSERVED BEHAVIOR."

    DO NOT make moral judgements about the expectation or the behavior, fact or event. Even if the expectation is bad, 
    the correct rule remains important, since there are legitimate cases where this is necessary (e.g., a simulation of 
    a person with a negative behavior, in the context of psychological research; or an evil character in a movie script).

    ## Examples

        Feedback: "Ana mentions she loved the proposed new food, a spicier flavor of gazpacho. However, this goes agains her known dislike
                    of spicy food."
        Rule: "Whenever I'm proposed spicy foods, I should reject the proposal, because I don't like spicy foods."
    """
    # llm decorator will handle the body of this function


@llm()
def combine_texts(*texts) -> str:
    """
    Given a list of input texts, this function combines them into a single text, ensuring that the
    output is coherent, consistent, and logically structured. In particular, the resulting combination
    must follow these rules:
        - The combination consolidates the information from the inputs. It **does not** just concatenate them.
        - Information that was repeated across the inputs is not repeated in the output, but rather unified and consolidated there.
        - The combination preserves all the essential information from the inputs, but it is not a simple copy of them.
        - If information from some inputs can be combined in a more concise formulation, this new formulation should be used in the output.
        This allows to reduce redundancy and improve clarity.
        - The combination might be larger than the sum of the inputs, since it preserves the information from the inputs.
        - If the various inputs seem to follow some common format or style, the output must follow that format or style too.
        - The combination can contain inconsistencies or contradictions, in case the inputs do.

    Args:
        *texts: A list of input texts to be combined.
    
    Returns:
        str: The combined text.
    """
    # llm decorator will handle the body of this function

